fix helm version

diff --git a/.github/workflows/infra-cicd.yml b/.github/workflows/infra-cicd.yml
--- a/.github/workflows/infra-cicd.yml
+++ b/.github/workflows/infra-cicd.yml
@@ -18,6 +18,8 @@ jobs:
         uses: azure/setup-helm@v3
         with:
           version: v3.9.0
+      - name: Verify Helm Installation
+        run: helm version || echo "Helm installation failed"
       - uses: actions/checkout@v2
       - name: Install aws-iam-authenticator
         run: |
